// <auto-generated />
using System;
using MessageApi.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MessageApi.Database.Migrations
{
    [DbContext(typeof(MessageContext))]
    partial class MessageContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MessageApi.Models.Account", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.HasKey("Username");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("MessageApi.Models.AccountGroup", b =>
                {
                    b.Property<string>("AccountUsername")
                        .HasColumnType("text");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.HasKey("AccountUsername", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("AccountGroup");
                });

            modelBuilder.Entity("MessageApi.Models.AccountMessage", b =>
                {
                    b.Property<string>("AccountUsername")
                        .HasColumnType("text");

                    b.Property<int>("MessageId")
                        .HasColumnType("integer");

                    b.HasKey("AccountUsername", "MessageId");

                    b.HasIndex("MessageId");

                    b.ToTable("AccountMessage");
                });

            modelBuilder.Entity("MessageApi.Models.Chat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("LastMessageId")
                        .HasColumnType("integer");

                    b.Property<string>("ReceiverUsername")
                        .HasColumnType("text");

                    b.Property<string>("SenderUsername")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LastMessageId")
                        .IsUnique();

                    b.HasIndex("ReceiverUsername");

                    b.HasIndex("SenderUsername");

                    b.ToTable("Chat");
                });

            modelBuilder.Entity("MessageApi.Models.GroupMessage", b =>
                {
                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<int>("MessageId")
                        .HasColumnType("integer");

                    b.HasKey("GroupId", "MessageId");

                    b.HasIndex("MessageId");

                    b.ToTable("GroupMessage");
                });

            modelBuilder.Entity("MessageApi.Models.Groups", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatorUsername")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("MessageApi.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateSent")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SenderUsername")
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SenderUsername");

                    b.ToTable("Message");
                });

            modelBuilder.Entity("MessageApi.Models.AccountGroup", b =>
                {
                    b.HasOne("MessageApi.Models.Account", "Account")
                        .WithMany("AccountGroups")
                        .HasForeignKey("AccountUsername")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MessageApi.Models.Groups", "Group")
                        .WithMany("GroupAccounts")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("MessageApi.Models.AccountMessage", b =>
                {
                    b.HasOne("MessageApi.Models.Account", "Account")
                        .WithMany("AccountMessages")
                        .HasForeignKey("AccountUsername")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MessageApi.Models.Message", "Message")
                        .WithMany("AccountMessages")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Message");
                });

            modelBuilder.Entity("MessageApi.Models.Chat", b =>
                {
                    b.HasOne("MessageApi.Models.Message", "LastMessage")
                        .WithOne("Chat")
                        .HasForeignKey("MessageApi.Models.Chat", "LastMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MessageApi.Models.Account", "Receiver")
                        .WithMany("ChatsReceived")
                        .HasForeignKey("ReceiverUsername");

                    b.HasOne("MessageApi.Models.Account", "Sender")
                        .WithMany("ChatsSent")
                        .HasForeignKey("SenderUsername");

                    b.Navigation("LastMessage");

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("MessageApi.Models.GroupMessage", b =>
                {
                    b.HasOne("MessageApi.Models.Groups", "Group")
                        .WithMany("GroupMessages")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MessageApi.Models.Message", "Message")
                        .WithMany("GroupMessages")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Message");
                });

            modelBuilder.Entity("MessageApi.Models.Message", b =>
                {
                    b.HasOne("MessageApi.Models.Account", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderUsername");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("MessageApi.Models.Account", b =>
                {
                    b.Navigation("AccountGroups");

                    b.Navigation("AccountMessages");

                    b.Navigation("ChatsReceived");

                    b.Navigation("ChatsSent");
                });

            modelBuilder.Entity("MessageApi.Models.Groups", b =>
                {
                    b.Navigation("GroupAccounts");

                    b.Navigation("GroupMessages");
                });

            modelBuilder.Entity("MessageApi.Models.Message", b =>
                {
                    b.Navigation("AccountMessages");

                    b.Navigation("Chat");

                    b.Navigation("GroupMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
