services:
  postgres:
    image: postgres:16
    container_name: message-api-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: message
      POSTGRES_DB: message-api
    ports:
      - "5004:5004"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d message-api"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data: